services:
  app:
    depends_on:
      pocketbase:
        condition: service_started
    environment:
      TZ: Asia/Kolkata
      POCKETBASE_URL: http://pocketbase:8088
      DB_PATH: /database/pb_data/data.db
      ENV: dev
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8008:8008
    volumes:
      - ./app:/app
      - ./database:/database
    command: uvicorn main:app --host 0.0.0.0 --port 8008 --reload

  pocketbase:
    build:
      context: .
      dockerfile: database/Dockerfile
    volumes:
      - ./database:/database
    ports:
      - "8088:8088"
    command: /pb/pocketbase serve --http=0.0.0.0:8088 --dir /database/pb_data
